// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("OCA-WaldoCompiler")]
[assembly: AssemblyDescriptionAttribute("Compiler for the waldo language, part of OCA - 93468fd879d49465915ede23a5ce1379c1f01a93")]
[assembly: AssemblyProductAttribute("OCA-WaldoCompiler")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
[assembly: InternalsVisibleToAttribute("OCA.WaldoCompiler.Test")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
