// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("OCA-Assembler")]
[assembly: AssemblyDescriptionAttribute("Assembler for OCA - f9cff13ff3d469f824fb2ef989be79f762fa6b8a")]
[assembly: AssemblyProductAttribute("OCA-Assembler")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
[assembly: InternalsVisibleToAttribute("OCA.Assembler.Test")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
